// Family Feud Season 26 Questions & Answers
// Source: https://mstiescott.neocities.org/feud26
// 763 main game questions from all 180 episodes (taped in 2024)
// Plus 83 Celebrity Family Feud questions = 846 total
// This file contains a curated selection across all answer categories (8, 7, 6, 5, and 4 answers)

export const questions = [

  // ── 8-ANSWER SURVEYS ──────────────────────────────────────────────────────

  {
    id: 1,
    question: "Name something a wife might shove in her husband's big mouth to shut him up.",
    answers: [
      { text: "Donut/Food", points: 64 },
      { text: "Sock", points: 20 },
      { text: "Rag", points: 3 },
      { text: "Her Fist", points: 3 },
      { text: "Her Boobs", points: 3 },
      { text: "Beer", points: 3 },
      { text: "Her Tongue", points: 2 },
      { text: "Napkin", points: 2 },
    ],
  },
  {
    id: 2,
    question: "Name a way your dad is like a bear.",
    answers: [
      { text: "Growls/Grouchy", points: 35 },
      { text: "Big & Round", points: 17 },
      { text: "Hairy", points: 14 },
      { text: "Hibernates/Snores", points: 12 },
      { text: "Gives Bear Hugs", points: 10 },
      { text: "Strong", points: 5 },
      { text: "Eats A Lot", points: 4 },
      { text: "Protective/Caring", points: 3 },
    ],
  },
  {
    id: 3,
    question: "Name something you might be holding while watching \"Family Feud\" on TV.",
    answers: [
      { text: "Remote", points: 46 },
      { text: "Food/Drink", points: 28 },
      { text: "Phone", points: 10 },
      { text: "Pet", points: 5 },
      { text: "Book To Read", points: 4 },
      { text: "Blanket", points: 2 },
      { text: "Myself", points: 2 },
      { text: "My Breath In Excitement!", points: 2 },
    ],
  },
  {
    id: 4,
    question: "Tell me a place Dracula takes girls on a first date.",
    answers: [
      { text: "Blood Bank", points: 45 },
      { text: "Castle/Dungeon", points: 15 },
      { text: "Cemetery/Morgue", points: 13 },
      { text: "Dark Bar/Club", points: 9 },
      { text: "Movie/Twilight Saga", points: 9 },
      { text: "Casket/Bed", points: 4 },
      { text: "Steakhouse", points: 2 },
      { text: "Moonlit Beach", points: 2 },
    ],
  },
  {
    id: 5,
    question: "Popeye would be easy to pick out of a police lineup just by his what?",
    answers: [
      { text: "Forearms/Muscles", points: 40 },
      { text: "Pipe", points: 34 },
      { text: "Sailor Suit/Cap", points: 7 },
      { text: "Tattoos", points: 6 },
      { text: "Squinting Eye", points: 6 },
      { text: "Bulbous Chin", points: 2 },
      { text: "Can Of Spinach", points: 2 },
      { text: "Voice/Laugh", points: 2 },
    ],
  },
  {
    id: 6,
    question: "Tell me another way people say \"grandpa.\"",
    answers: [
      { text: "Papa", points: 35 },
      { text: "Pops/Pop-Pop", points: 23 },
      { text: "Gramps/Grampy", points: 14 },
      { text: "Paw-Paw", points: 9 },
      { text: "Granddad", points: 8 },
      { text: "Grandfather", points: 6 },
      { text: "Opa", points: 2 },
      { text: "Pappy", points: 2 },
    ],
  },
  {
    id: 7,
    question: "Tell me why you think your house is haunted.",
    answers: [
      { text: "Noises/Voices", points: 68 },
      { text: "Ghosts!", points: 8 },
      { text: "Doors Open/Close", points: 7 },
      { text: "Things Move/Vanish", points: 6 },
      { text: "I Don't!", points: 3 },
      { text: "Cold Breezes", points: 2 },
      { text: "Dead Animals", points: 2 },
      { text: "Gets Dusty/Dirty", points: 2 },
    ],
  },
  {
    id: 8,
    question: "Name something a dog eats that you wouldn't eat no matter how hungry you were.",
    answers: [
      { text: "Poop", points: 59 },
      { text: "Dog Food/Raw", points: 23 },
      { text: "Vomit", points: 3 },
      { text: "Bones", points: 3 },
      { text: "Trash", points: 3 },
      { text: "Liver", points: 3 },
      { text: "Grass", points: 2 },
      { text: "Dead Animal/Bugs", points: 2 },
    ],
  },
  {
    id: 9,
    question: "We asked 100 married women... What do you wish your husband bought you at least once a month?",
    answers: [
      { text: "Flowers", points: 40 },
      { text: "Dinner", points: 25 },
      { text: "Candy/Treats", points: 12 },
      { text: "Vacation", points: 9 },
      { text: "Jewelry", points: 3 },
      { text: "Massage/Spa Day", points: 3 },
      { text: "Champagne/Booze", points: 3 },
      { text: "Housekeeper", points: 3 },
    ],
  },
  {
    id: 10,
    question: "Tell me a word that women use for a very attractive man.",
    answers: [
      { text: "Hot/Hottie", points: 36 },
      { text: "Handsome", points: 27 },
      { text: "Hunk", points: 19 },
      { text: "Stud", points: 6 },
      { text: "Fine", points: 3 },
      { text: "Sexy", points: 3 },
      { text: "Cute/Cutie", points: 2 },
      { text: "Yummy", points: 2 },
    ],
  },
  {
    id: 11,
    question: "If your boss were a \"Sesame Street\" character, which one would he be?",
    answers: [
      { text: "Oscar The Grouch", points: 36 },
      { text: "Big Bird", points: 27 },
      { text: "Elmo", points: 12 },
      { text: "Cookie Monster", points: 8 },
      { text: "Ernie", points: 6 },
      { text: "Kermit The Frog", points: 5 },
      { text: "Bert", points: 2 },
      { text: "Grover", points: 2 },
    ],
  },
  {
    id: 12,
    question: "Name something you'd stop doing in the nude if you moved back in with your parents.",
    answers: [
      { text: "Sleeping", points: 50 },
      { text: "Walking Around", points: 25 },
      { text: "Housework", points: 7 },
      { text: "Cooking", points: 5 },
      { text: "Sunbathe/Pool Time", points: 4 },
      { text: "Dancing", points: 2 },
      { text: "Boinking", points: 2 },
      { text: "Anything At All!", points: 2 },
    ],
  },
  {
    id: 13,
    question: "Name a bird that's also the name of a sports team.",
    answers: [
      { text: "Cardinals", points: 41 },
      { text: "Eagles", points: 16 },
      { text: "Falcons", points: 10 },
      { text: "Ravens", points: 9 },
      { text: "Orioles", points: 8 },
      { text: "Blue Jays", points: 6 },
      { text: "Seahawks", points: 4 },
      { text: "Pelicans", points: 3 },
    ],
  },
  {
    id: 14,
    question: "Name something you do at a rock concert but not at a classical music concert.",
    answers: [
      { text: "Scream", points: 31 },
      { text: "Dance/Mosh Pit", points: 20 },
      { text: "Sing Along", points: 13 },
      { text: "Stand", points: 10 },
      { text: "Wave Lighter/Phone", points: 7 },
      { text: "Wear Jeans", points: 6 },
      { text: "Get Drunk", points: 6 },
      { text: "Pass A Joint", points: 4 },
    ],
  },
  {
    id: 15,
    question: "What would be the best thing about being besties with Beyoncé?",
    answers: [
      { text: "All Her $$$", points: 28 },
      { text: "Music/Free Tickets", points: 27 },
      { text: "Travel The World", points: 14 },
      { text: "Great Parties", points: 11 },
      { text: "Fame", points: 8 },
      { text: "Celeb Pals/Jay-Z", points: 4 },
      { text: "Michelin Star Food", points: 3 },
      { text: "Designer Clothes", points: 2 },
    ],
  },
  {
    id: 16,
    question: "Name a part of your body you could break and still do your job.",
    answers: [
      { text: "Toe", points: 23 },
      { text: "Nose", points: 20 },
      { text: "Leg", points: 17 },
      { text: "Finger", points: 12 },
      { text: "Foot", points: 12 },
      { text: "Arm/Elbow", points: 5 },
      { text: "Rib", points: 5 },
      { text: "Tooth", points: 3 },
    ],
  },
  {
    id: 17,
    question: "Tell me a reason you haven't brushed your teeth for a few days.",
    answers: [
      { text: "Sore Mouth/Sick", points: 54 },
      { text: "No Brush/Camping", points: 17 },
      { text: "Lazy/Tired", points: 11 },
      { text: "Too Busy", points: 4 },
      { text: "No Teeth", points: 4 },
      { text: "Been Too Drunk", points: 2 },
      { text: "Sad/About Breakup", points: 2 },
      { text: "Dead", points: 2 },
    ],
  },
  {
    id: 18,
    question: "Name something a female dolphin might find sexy about her mate.",
    answers: [
      { text: "Fine Fins/Tail", points: 41 },
      { text: "Cute Face/Nose", points: 18 },
      { text: "Swim/Jump Skills", points: 14 },
      { text: "Sultry Sound", points: 9 },
      { text: "Nice Blowhole", points: 7 },
      { text: "Fab Phallus", points: 3 },
      { text: "Sleek Skin", points: 3 },
      { text: "Size/Shape", points: 2 },
    ],
  },
  {
    id: 19,
    question: "Name something Dorothy saw in Oz and said, \"We don't have that in Kansas.\"",
    answers: [
      { text: "Yellow Brick Road", points: 28 },
      { text: "Munchkins", points: 20 },
      { text: "Witches", points: 19 },
      { text: "Flying Monkeys", points: 15 },
      { text: "Color-Changing Horse", points: 5 },
      { text: "Tin Man", points: 4 },
      { text: "Magic Poppies", points: 3 },
      { text: "The Wizard", points: 2 },
    ],
  },
  {
    id: 20,
    question: "Name a reason a man might say he has a beard.",
    answers: [
      { text: "Looks Hot/Manly", points: 28 },
      { text: "Hide Zits/Scar", points: 15 },
      { text: "Unattractive/Jawline", points: 14 },
      { text: "Too Lazy To Shave", points: 13 },
      { text: "Stay Warm", points: 10 },
      { text: "He's Santa", points: 6 },
      { text: "Because He Does!", points: 5 },
      { text: "Look Older", points: 5 },
    ],
  },
  {
    id: 21,
    question: "Name something from a pet store that Batman might buy Catwoman for her birthday.",
    answers: [
      { text: "Catnip", points: 27 },
      { text: "Collar & Leash", points: 21 },
      { text: "Cat Food/Treats", points: 16 },
      { text: "A Kitten", points: 12 },
      { text: "Ball/Toy", points: 8 },
      { text: "Scratching Post", points: 7 },
      { text: "Rats/Mice", points: 3 },
      { text: "Litter Box", points: 2 },
    ],
  },
  {
    id: 22,
    question: "We asked 100 women... What do you learn about a man's past that tells you there's no future with him?",
    answers: [
      { text: "Man-Ho", points: 23 },
      { text: "Jail/Most Wanted", points: 23 },
      { text: "Mom Drama/Lives With", points: 22 },
      { text: "Many Divorces", points: 10 },
      { text: "Liar", points: 7 },
      { text: "Lots Of Kids", points: 4 },
      { text: "Cheap", points: 4 },
      { text: "Can't Keep A Job", points: 3 },
    ],
  },
  {
    id: 23,
    question: "We asked 100 married women... Name a command that would make both your husband and your dog think you were talking to them.",
    answers: [
      { text: "Be Quiet!", points: 21 },
      { text: "Sit!", points: 17 },
      { text: "Come Here!", points: 12 },
      { text: "Stop!", points: 12 },
      { text: "Dinner!/Eat!", points: 12 },
      { text: "Stay!", points: 10 },
      { text: "Down, Boy!", points: 7 },
      { text: "Go For A Walk?", points: 5 },
    ],
  },
  {
    id: 24,
    question: "We asked 100 men... Give me one word that describes how you like your food and your women.",
    answers: [
      { text: "Hot", points: 51 },
      { text: "Spicy", points: 14 },
      { text: "Warm", points: 10 },
      { text: "Sweet", points: 7 },
      { text: "Tender", points: 4 },
      { text: "Cheap", points: 3 },
      { text: "Satisfying", points: 3 },
      { text: "Seasoned", points: 3 },
    ],
  },
  {
    id: 25,
    question: "The world is ending in one hour. Where do you tell the Uber driver to take you?",
    answers: [
      { text: "Home/Family's", points: 47 },
      { text: "Church", points: 13 },
      { text: "Beach", points: 11 },
      { text: "Bar", points: 9 },
      { text: "Eatery/Chili's", points: 7 },
      { text: "Casino/Vegas", points: 3 },
      { text: "Store/Shopping", points: 3 },
      { text: "Strip Joint", points: 2 },
    ],
  },
  {
    id: 26,
    question: "Name something a good basketball player gets a lot of.",
    answers: [
      { text: "Baskets/Shots", points: 33 },
      { text: "Money", points: 31 },
      { text: "Praise/Fans", points: 17 },
      { text: "Sex/Dates", points: 4 },
      { text: "Rebounds", points: 3 },
      { text: "Exercise", points: 3 },
      { text: "Assists", points: 2 },
      { text: "Practice", points: 2 },
    ],
  },
  {
    id: 27,
    question: "Name something you say on a date even if you don't mean it.",
    answers: [
      { text: "Look Great/Cute!", points: 31 },
      { text: "Nice Time!", points: 20 },
      { text: "I Like/Love You!", points: 11 },
      { text: "See Again/Call", points: 11 },
      { text: "So Interesting!", points: 7 },
      { text: "Thank You!", points: 6 },
      { text: "Great Restaurant!", points: 5 },
      { text: "Nice To Meet U!", points: 4 },
    ],
  },
  {
    id: 28,
    question: "How does a man get a girlfriend who's out of his league?",
    answers: [
      { text: "Be Rich", points: 31 },
      { text: "Buy Gifts/Bling", points: 16 },
      { text: "Funny/Charming", points: 10 },
      { text: "Seductive Cologne", points: 10 },
      { text: "Be A Good Man", points: 10 },
      { text: "Confidence", points: 10 },
      { text: "Lie", points: 6 },
      { text: "Be Persistent!", points: 2 },
    ],
  },
  {
    id: 29,
    question: "We asked 100 women... Name something your man has in common with peanut butter.",
    answers: [
      { text: "Smooth", points: 28 },
      { text: "Nutty", points: 21 },
      { text: "Tasty", points: 15 },
      { text: "Chunky/Thick", points: 10 },
      { text: "Sweet", points: 9 },
      { text: "Sticky", points: 4 },
      { text: "Creamy", points: 4 },
      { text: "Salty", points: 4 },
    ],
  },
  {
    id: 30,
    question: "Fill in the blank: I may be terrible at ______, but I still love doing it.",
    answers: [
      { text: "Sports/Fishing", points: 28 },
      { text: "Singing", points: 21 },
      { text: "Cooking", points: 14 },
      { text: "Dancing", points: 12 },
      { text: "Shagging", points: 12 },
      { text: "Drawing/Painting", points: 4 },
      { text: "Driving", points: 2 },
      { text: "Gambling", points: 2 },
    ],
  },
  {
    id: 31,
    question: "A soccer player would be laughed off the field if he wore what kind of shoes?",
    answers: [
      { text: "High Heels", points: 27 },
      { text: "Ballet/Dance", points: 18 },
      { text: "Flip-Flops/Sandals", points: 17 },
      { text: "Crocs", points: 11 },
      { text: "Sneakers/Tennies", points: 9 },
      { text: "Dress Shoes", points: 6 },
      { text: "Bowling Shoes", points: 4 },
      { text: "Clown Shoes", points: 3 },
    ],
  },
  {
    id: 32,
    question: "We asked 100 single men... What's the single worst thing that can happen on a date?",
    answers: [
      { text: "No-Show", points: 22 },
      { text: "Forget Wallet", points: 21 },
      { text: "Raging Bowel/Gas", points: 18 },
      { text: "Argue", points: 10 },
      { text: "Lame/No Convo", points: 9 },
      { text: "She Sneaks Out", points: 6 },
      { text: "30-Second Sex", points: 5 },
      { text: "Ex Shows Up", points: 4 },
    ],
  },
  {
    id: 33,
    question: "There's a grizzly bear outside of your tent. What do you do?",
    answers: [
      { text: "Play Dead/Stay Put", points: 52 },
      { text: "Yell/Make Noise", points: 14 },
      { text: "Pray!", points: 8 },
      { text: "Run", points: 7 },
      { text: "Shoot Off Gun", points: 5 },
      { text: "Poo/Pee Self", points: 4 },
      { text: "Cry", points: 2 },
      { text: "Sacrifice Mate/Pal", points: 2 },
    ],
  },
  {
    id: 34,
    question: "Your hot date goes in for a kiss, but they have a cold sore. What do you do?",
    answers: [
      { text: "Turn Away/Duck", points: 48 },
      { text: "Give Cheek Kiss", points: 11 },
      { text: "Say \"Ew, No!\"", points: 8 },
      { text: "Kiss 'Em Anyway", points: 8 },
      { text: "Run!/\"Toodles!\"", points: 6 },
      { text: "Push 'Em Away", points: 5 },
      { text: "Fake Cough/Sneeze", points: 5 },
      { text: "Hand On Mouth", points: 3 },
    ],
  },
  {
    id: 35,
    question: "Name an alcoholic beverage you drink poolside.",
    answers: [
      { text: "Beer", points: 39 },
      { text: "Margarita", points: 24 },
      { text: "Pina Colada", points: 8 },
      { text: "Mai Tai", points: 6 },
      { text: "Wine", points: 6 },
      { text: "Daiquiri", points: 5 },
      { text: "Long Island", points: 3 },
      { text: "Mimosa", points: 3 },
    ],
  },
  {
    id: 36,
    question: "Name a food that would be dangerous to fry when you're naked.",
    answers: [
      { text: "Bacon", points: 35 },
      { text: "Chicken", points: 23 },
      { text: "Fries/Potatoes", points: 16 },
      { text: "Turkey", points: 9 },
      { text: "Fish", points: 5 },
      { text: "Eggs", points: 2 },
      { text: "Onion Rings", points: 2 },
      { text: "Sausage/Franks", points: 2 },
    ],
  },
  {
    id: 37,
    question: "Tell me something a drunk person might do just like a baby.",
    answers: [
      { text: "Cry/Whine", points: 35 },
      { text: "Go In Their Pants", points: 19 },
      { text: "Sleep/Snore", points: 16 },
      { text: "Babble", points: 6 },
      { text: "Drool", points: 5 },
      { text: "Puke", points: 5 },
      { text: "Crawl", points: 4 },
      { text: "Walk", points: 4 },
    ],
  },
  {
    id: 38,
    question: "If you were covered in quills like a porcupine, name something you might have trouble doing.",
    answers: [
      { text: "Sleepin'", points: 24 },
      { text: "Hug & Kissin'", points: 22 },
      { text: "Gettin' Dressed", points: 13 },
      { text: "Sittin'", points: 8 },
      { text: "The Naughty", points: 8 },
      { text: "Bathin'", points: 7 },
      { text: "Scratchin'", points: 7 },
      { text: "Potty/Wipin'", points: 5 },
    ],
  },
  {
    id: 39,
    question: "Mirror, mirror, on the wall, who's the richest TV host of them all?",
    answers: [
      { text: "Steve Harvey", points: 42 },
      { text: "Pat Sajak", points: 14 },
      { text: "Oprah", points: 13 },
      { text: "Ryan Seacrest", points: 12 },
      { text: "Jay Leno", points: 3 },
      { text: "Ellen", points: 3 },
      { text: "Jimmy Fallon", points: 3 },
      { text: "Jimmy Kimmel", points: 3 },
    ],
  },
  {
    id: 40,
    question: "Name a reason someone might be squirming.",
    answers: [
      { text: "Gotta Pee/Poo", points: 40 },
      { text: "Lying/Guilty", points: 19 },
      { text: "Itchy/Hemorrhoids", points: 11 },
      { text: "Nervous/Scared", points: 10 },
      { text: "See Critter/Bug", points: 5 },
      { text: "Pain/Dentist", points: 5 },
      { text: "Sitting/Uncomf.", points: 4 },
      { text: "Bored/Restless", points: 2 },
    ],
  },
  {
    id: 41,
    question: "Name a type of music that makes you want to get up and dance.",
    answers: [
      { text: "Hip-Hop", points: 20 },
      { text: "Pop", points: 15 },
      { text: "Country", points: 10 },
      { text: "Rock/Metal", points: 9 },
      { text: "Techno/EDM", points: 9 },
      { text: "Disco", points: 7 },
      { text: "R&B/Soul", points: 7 },
      { text: "Reggae", points: 6 },
    ],
  },
  {
    id: 42,
    question: "Name a reason you couldn't be paid to go to your high school reunion.",
    answers: [
      { text: "Hated Everyone", points: 45 },
      { text: "Gained Weight", points: 16 },
      { text: "Boring/No Interest", points: 10 },
      { text: "Ex Is Going", points: 9 },
      { text: "Too Far", points: 6 },
      { text: "Had Bad Reputation", points: 3 },
      { text: "Didn't Graduate", points: 2 },
      { text: "I Look 90", points: 2 },
    ],
  },
  {
    id: 43,
    question: "Fill in the blank: I'm so happy, I could ______.",
    answers: [
      { text: "Cry", points: 43 },
      { text: "Scream", points: 12 },
      { text: "Burst/Explode", points: 9 },
      { text: "Poop/Fart", points: 8 },
      { text: "Jump For Joy", points: 6 },
      { text: "Sing", points: 5 },
      { text: "Dance", points: 5 },
      { text: "Smile Forever!", points: 5 },
    ],
  },
  {
    id: 44,
    question: "Name something a crab might crab about to its friends.",
    answers: [
      { text: "Get Eaten/Caught", points: 25 },
      { text: "Heat/Cold", points: 17 },
      { text: "Pollution", points: 16 },
      { text: "Sand Everywhere", points: 10 },
      { text: "Food/Fish", points: 8 },
      { text: "Cramped Shell", points: 8 },
      { text: "Sore Pincers", points: 7 },
      { text: "Bein' A Shortie", points: 2 },
    ],
  },
  {
    id: 45,
    question: "Name something that makes a guy a great kisser.",
    answers: [
      { text: "The Lips!", points: 38 },
      { text: "No Slobber", points: 10 },
      { text: "Passion/Love", points: 10 },
      { text: "Tongue Skills", points: 10 },
      { text: "Practice", points: 8 },
      { text: "Fresh Breath", points: 7 },
      { text: "Gentle", points: 7 },
      { text: "Holds Me", points: 2 },
    ],
  },
  {
    id: 46,
    question: "Who is the greatest rapper of all time?",
    answers: [
      { text: "Snoop Dogg", points: 25 },
      { text: "Tupac", points: 20 },
      { text: "Eminem", points: 16 },
      { text: "Dr. Dre", points: 9 },
      { text: "LL Cool J", points: 5 },
      { text: "The Notorious B.I.G.", points: 5 },
      { text: "50 Cent", points: 3 },
      { text: "Jay-Z", points: 3 },
    ],
  },
  {
    id: 47,
    question: "Name a creature you might try to escape from by climbing a tree.",
    answers: [
      { text: "Vicious Chihuahua", points: 31 },
      { text: "Bear", points: 25 },
      { text: "Lion", points: 9 },
      { text: "Wolf", points: 6 },
      { text: "Gator/Croc", points: 5 },
      { text: "Moose", points: 4 },
      { text: "Hippo", points: 3 },
      { text: "Rat/Mouse", points: 3 },
    ],
  },
  {
    id: 48,
    question: "Name something you hide before giving someone a tour of your house.",
    answers: [
      { text: "Dirty Clothes", points: 43 },
      { text: "Adult Toys", points: 15 },
      { text: "Dirty Dishes", points: 10 },
      { text: "Jewelry", points: 7 },
      { text: "Nudie Pix/Flix", points: 4 },
      { text: "Medications", points: 4 },
      { text: "$/Wallet", points: 3 },
      { text: "Litter Box", points: 3 },
    ],
  },
  {
    id: 49,
    question: "Name a dangerous animal that the worst petting zoo ever would have in it.",
    answers: [
      { text: "Lion", points: 24 },
      { text: "Bear", points: 16 },
      { text: "Tiger", points: 10 },
      { text: "Shark", points: 10 },
      { text: "Gator/Croc", points: 10 },
      { text: "Snake/Cobra", points: 6 },
      { text: "Porcupine", points: 4 },
      { text: "Hippo", points: 3 },
    ],
  },
  {
    id: 50,
    question: "Past or present, name a celebrity who's been married at least three times.",
    answers: [
      { text: "Elizabeth Taylor", points: 43 },
      { text: "Jennifer Lopez", points: 11 },
      { text: "Steve Harvey", points: 9 },
      { text: "Zsa Zsa Gabor", points: 7 },
      { text: "Donald Trump", points: 6 },
      { text: "Angelina Jolie", points: 4 },
      { text: "Kim Kardashian", points: 4 },
      { text: "Tom Cruise", points: 3 },
    ],
  },

  // ── 7-ANSWER SURVEYS ──────────────────────────────────────────────────────

  {
    id: 51,
    question: "A husband wouldn't like his wife bringing her work husband where?",
    answers: [
      { text: "Home/To Bed", points: 81 },
      { text: "Hotel/Vacay", points: 6 },
      { text: "Restaurant/Nobu", points: 4 },
      { text: "Bar/Club", points: 3 },
      { text: "Church", points: 2 },
      { text: "Party/Hubby's B-Day", points: 2 },
      { text: "Store/Lingerie Shop", points: 2 },
    ],
  },
  {
    id: 52,
    question: "Name a place you'd hate to discover a two-way mirror.",
    answers: [
      { text: "Bathroom", points: 51 },
      { text: "Dressing Room", points: 31 },
      { text: "Doctor's Office", points: 5 },
      { text: "Gym/Locker Room", points: 5 },
      { text: "Hotel Room", points: 4 },
      { text: "At Work", points: 2 },
      { text: "My Bedroom", points: 2 },
    ],
  },
  {
    id: 53,
    question: "We asked 100 men... You're getting married in the morning. Tell me what you're doing tonight.",
    answers: [
      { text: "Party/Boozing", points: 50 },
      { text: "Sleeping", points: 22 },
      { text: "Sex/With Everyone", points: 10 },
      { text: "Running Away", points: 6 },
      { text: "Dinner/With Fam", points: 5 },
      { text: "Praying", points: 4 },
      { text: "Questioning Decision", points: 3 },
    ],
  },
  {
    id: 54,
    question: "Name something a kid does to convince mom and dad they're too sick for school.",
    answers: [
      { text: "Cough", points: 46 },
      { text: "Puke/Gag Self", points: 25 },
      { text: "Fake Fever", points: 12 },
      { text: "Cry/Moan", points: 7 },
      { text: "Sneeze/Blow Nose", points: 3 },
      { text: "Stomachache", points: 3 },
      { text: "Stay In Bed", points: 3 },
    ],
  },
  {
    id: 55,
    question: "We asked 100 men... You love a naked woman just as long as it isn't your who?",
    answers: [
      { text: "Mom", points: 44 },
      { text: "Mother-In-Law", points: 27 },
      { text: "Sister", points: 15 },
      { text: "Wife", points: 4 },
      { text: "Grandma", points: 4 },
      { text: "Daughter", points: 3 },
      { text: "Ex", points: 2 },
    ],
  },
  {
    id: 56,
    question: "If Batman got married, name something his wife might tell him he has to get rid of.",
    answers: [
      { text: "Costume", points: 42 },
      { text: "Clingy Robin", points: 25 },
      { text: "Batmobile", points: 16 },
      { text: "Batcave", points: 7 },
      { text: "Job/Late Night Calls", points: 4 },
      { text: "Babes/Catwoman", points: 3 },
      { text: "Weapons", points: 2 },
    ],
  },
  {
    id: 57,
    question: "Name someone you'd be surprised just lit up a joint.",
    answers: [
      { text: "Parents", points: 34 },
      { text: "Clergy/Sister Ethel", points: 24 },
      { text: "Politician/Prez", points: 20 },
      { text: "Grandparents", points: 7 },
      { text: "Spouse", points: 5 },
      { text: "Celeb/Oprah", points: 5 },
      { text: "Doctor", points: 4 },
    ],
  },
  {
    id: 58,
    question: "We asked 100 women... You know there's been a man in your house if you can smell what?",
    answers: [
      { text: "Bad Cologne", points: 33 },
      { text: "Sweaty Pits/Feet", points: 32 },
      { text: "Beer", points: 15 },
      { text: "Farts", points: 9 },
      { text: "Cigars/Tobacco", points: 4 },
      { text: "Burnt Food/Old Pizza", points: 4 },
      { text: "Gasoline/Oil", points: 2 },
    ],
  },
  {
    id: 59,
    question: "You hope a restaurant chef doesn't do what while he's making your food?",
    answers: [
      { text: "Sneeze/Cough", points: 70 },
      { text: "Spit", points: 15 },
      { text: "Pick/Blow Nose", points: 4 },
      { text: "Get Sick/Puke", points: 3 },
      { text: "Sweat", points: 2 },
      { text: "Smoke Profusely", points: 2 },
      { text: "Go To Bathroom", points: 2 },
    ],
  },
  {
    id: 60,
    question: "Name a stand-up comic's worst fear when they're onstage.",
    answers: [
      { text: "No Laughs/Silence", points: 54 },
      { text: "Hecklers", points: 13 },
      { text: "Forget/Botch Joke", points: 11 },
      { text: "Get Booed", points: 9 },
      { text: "Stage Fright", points: 6 },
      { text: "Crowd Throws Stuff", points: 3 },
      { text: "Slapped/Will Smith", points: 2 },
    ],
  },
  {
    id: 61,
    question: "We asked 100 married women... When kids misbehave, you take away their allowance. When your husband misbehaves, you take away what?",
    answers: [
      { text: "Sexy Time", points: 48 },
      { text: "His Food", points: 15 },
      { text: "His Allowance", points: 15 },
      { text: "His Beer", points: 11 },
      { text: "TV Time", points: 4 },
      { text: "House Keys", points: 3 },
      { text: "His Car", points: 2 },
    ],
  },
  {
    id: 62,
    question: "Name something about someone's lips that can be a real turnoff.",
    answers: [
      { text: "Chapped", points: 46 },
      { text: "Too Big/Fillers", points: 26 },
      { text: "Oozing Sores", points: 9 },
      { text: "Too Thin", points: 7 },
      { text: "Dirty/White Gunk", points: 4 },
      { text: "Pouty/Pursed", points: 3 },
      { text: "Pierced", points: 3 },
    ],
  },
  {
    id: 63,
    question: "If a witch and a wizard got divorced, she might complain that he got the what?",
    answers: [
      { text: "Wand", points: 43 },
      { text: "Good Spells/Potions", points: 18 },
      { text: "Broom", points: 17 },
      { text: "Cauldron", points: 13 },
      { text: "Crystal Ball", points: 3 },
      { text: "Castle", points: 2 },
      { text: "Hat", points: 2 },
    ],
  },
  {
    id: 64,
    question: "Name something of his wife's a man might wear because all of his are dirty.",
    answers: [
      { text: "Socks", points: 39 },
      { text: "Silk Panties", points: 26 },
      { text: "Shirt", points: 20 },
      { text: "Pants", points: 4 },
      { text: "Coat/Hoodie", points: 3 },
      { text: "Bathrobe", points: 3 },
      { text: "Hat", points: 3 },
    ],
  },
  {
    id: 65,
    question: "We asked 100 married men... Tell me a B word that describes your wife's bottom.",
    answers: [
      { text: "Beautiful", points: 37 },
      { text: "Big", points: 21 },
      { text: "Bouncy", points: 13 },
      { text: "Bodacious", points: 13 },
      { text: "Blubbery", points: 9 },
      { text: "Booty/Licious", points: 3 },
      { text: "Bubble", points: 2 },
    ],
  },
  {
    id: 66,
    question: "Name something your mother used to do when you talked back.",
    answers: [
      { text: "Spank Me", points: 55 },
      { text: "Time Out/Go To Room", points: 11 },
      { text: "Ground Me", points: 10 },
      { text: "Soap In Mouth", points: 10 },
      { text: "Yell/Cuss Out", points: 8 },
      { text: "Death Stare", points: 2 },
      { text: "Tell Dad", points: 2 },
    ],
  },
  {
    id: 67,
    question: "Tell me something that's not food that people chew.",
    answers: [
      { text: "Gum", points: 54 },
      { text: "Tobacco/Dip", points: 19 },
      { text: "Fingernail/Toenail", points: 16 },
      { text: "Toothpick", points: 3 },
      { text: "Cigar", points: 2 },
      { text: "Grass/Hay", points: 2 },
      { text: "Pen/Pencil", points: 2 },
    ],
  },
  {
    id: 68,
    question: "We asked 100 single women... You love being single, but sometimes you want a man around to do what?",
    answers: [
      { text: "Chores/Yard Work", points: 32 },
      { text: "Repairs", points: 29 },
      { text: "Go To Dinner", points: 15 },
      { text: "Talk To", points: 7 },
      { text: "Reach Top Shelf", points: 6 },
      { text: "Pay Bills/Make $", points: 5 },
      { text: "Affection/Sex", points: 4 },
    ],
  },

  // ── 6-ANSWER SURVEYS ──────────────────────────────────────────────────────

  {
    id: 69,
    question: "Name something that some people jump into and others ease into.",
    answers: [
      { text: "Pool/Water", points: 69 },
      { text: "Relationship/Sex", points: 22 },
      { text: "Bed/Furniture", points: 3 },
      { text: "Good Book", points: 2 },
      { text: "Car", points: 2 },
      { text: "New Job", points: 2 },
    ],
  },
  {
    id: 70,
    question: "Name a word or phrase that describes how eggs are prepared that also describes you.",
    answers: [
      { text: "Scrambled", points: 47 },
      { text: "Over Easy", points: 19 },
      { text: "Boiled/Hard-Boiled", points: 14 },
      { text: "Sunny-Side Up", points: 11 },
      { text: "Deviled", points: 7 },
      { text: "Fried", points: 2 },
    ],
  },
  {
    id: 71,
    question: "Name a musical instrument a person plays that would give them strong, kissable lips.",
    answers: [
      { text: "Trumpet", points: 45 },
      { text: "Tuba", points: 17 },
      { text: "Flute", points: 16 },
      { text: "Sax", points: 15 },
      { text: "Trombone", points: 5 },
      { text: "French Horn", points: 2 },
    ],
  },
  {
    id: 72,
    question: "Instead of leaving her shoe at the ball, today's Cinderella might leave her what?",
    answers: [
      { text: "Phone", points: 60 },
      { text: "Thong/Clothes", points: 23 },
      { text: "Card/Number", points: 6 },
      { text: "Purse/Wallet", points: 4 },
      { text: "Jewelry/Bracelet", points: 4 },
      { text: "Tesla/Keys", points: 2 },
    ],
  },
  {
    id: 73,
    question: "Name something a baseball player does on the field that would be unacceptable in church.",
    answers: [
      { text: "Spit/Chew", points: 53 },
      { text: "Adjust/Scratch", points: 26 },
      { text: "Cuss", points: 10 },
      { text: "Play Ball/Slide", points: 6 },
      { text: "Tap/Throw Bat", points: 2 },
      { text: "Wear A Hat", points: 2 },
    ],
  },
  {
    id: 74,
    question: "Name something a guy does when he walks past a beautiful woman.",
    answers: [
      { text: "Turns & Gawks", points: 68 },
      { text: "Whistles", points: 17 },
      { text: "Smiles", points: 6 },
      { text: "Keeps Going/Ignores", points: 3 },
      { text: "Dopey Comment", points: 2 },
      { text: "Winks", points: 2 },
    ],
  },
  {
    id: 75,
    question: "Tell me a kind of flower that a lot of grandmas have as a first name.",
    answers: [
      { text: "Rose", points: 58 },
      { text: "Daisy", points: 13 },
      { text: "Lily", points: 12 },
      { text: "Iris", points: 6 },
      { text: "Violet", points: 6 },
      { text: "Petunia", points: 3 },
    ],
  },
  {
    id: 76,
    question: "Name a reason why coworkers would keep moving out of the cubicle next to you.",
    answers: [
      { text: "I Stink", points: 52 },
      { text: "Loud/Chatty", points: 32 },
      { text: "I'm Rude/Mean", points: 5 },
      { text: "They Get Fired", points: 5 },
      { text: "I Eat Gross Food", points: 2 },
      { text: "I'm Messy", points: 2 },
    ],
  },
  {
    id: 77,
    question: "Name something you do with your eyes to flirt with someone.",
    answers: [
      { text: "Wink", points: 45 },
      { text: "Bat Them", points: 38 },
      { text: "Stare/Eye Contact", points: 8 },
      { text: "Raise Eyebrows", points: 3 },
      { text: "Open Wide", points: 2 },
      { text: "Squint", points: 2 },
    ],
  },
  {
    id: 78,
    question: "When you walk into a hospital, what might you see on the floor that would make you walk back out?",
    answers: [
      { text: "Blood", points: 45 },
      { text: "A Body/An Arm", points: 27 },
      { text: "Barf", points: 12 },
      { text: "Pee/Poo", points: 6 },
      { text: "Roaches/Critters", points: 5 },
      { text: "Dirt/Trash", points: 3 },
    ],
  },
  {
    id: 79,
    question: "Name something your cheap friends bring to your party.",
    answers: [
      { text: "Leftovers/Cheap Food", points: 39 },
      { text: "Cheap Liquor", points: 37 },
      { text: "Cups/Paper Plates", points: 8 },
      { text: "Bupkis", points: 8 },
      { text: "Water/Ice", points: 4 },
      { text: "Paper Towels", points: 2 },
    ],
  },
  {
    id: 80,
    question: "Name something Steve Harvey and Mr. Clean have in common.",
    answers: [
      { text: "Shiny Bald Heads", points: 77 },
      { text: "They're Men", points: 8 },
      { text: "They're Famous", points: 7 },
      { text: "Cute/Smiles", points: 3 },
      { text: "Muscular Build", points: 2 },
      { text: "They're Clean", points: 2 },
    ],
  },

  // ── 5-ANSWER SURVEYS ──────────────────────────────────────────────────────

  {
    id: 81,
    question: "We asked 100 single men... What do you do if your date talks nonstop?",
    answers: [
      { text: "Leave/Pee Break", points: 40 },
      { text: "Listen/Nod & Smile", points: 31 },
      { text: "Ignore Her", points: 16 },
      { text: "Kiss Her", points: 11 },
      { text: "Change Subject", points: 2 },
    ],
  },
  {
    id: 82,
    question: "Name something scientists would be excited to find on Mars.",
    answers: [
      { text: "Life/Fossils", points: 87 },
      { text: "Water", points: 6 },
      { text: "Ruins/Buildings", points: 2 },
      { text: "Diamonds/Gold", points: 2 },
      { text: "Food/Mars Bars", points: 2 },
    ],
  },
  {
    id: 83,
    question: "Name something you fish for.",
    answers: [
      { text: "Fish/Seafood", points: 66 },
      { text: "A Compliment", points: 16 },
      { text: "My Keys", points: 8 },
      { text: "$$$/Change", points: 5 },
      { text: "Answer/Info", points: 4 },
    ],
  },
  {
    id: 84,
    question: "If you don't like your date, you might put what between you on the couch?",
    answers: [
      { text: "Pillow", points: 64 },
      { text: "Pet/Python", points: 22 },
      { text: "Food/With Garlic", points: 9 },
      { text: "A Lot Of Space", points: 2 },
      { text: "Pal/Uncle Ernie", points: 2 },
    ],
  },
  {
    id: 85,
    question: "We asked 100 men... Name an accent you fake at the bar to attract women.",
    answers: [
      { text: "British", points: 58 },
      { text: "Aussie", points: 16 },
      { text: "French", points: 15 },
      { text: "Italian", points: 8 },
      { text: "Irish", points: 2 },
    ],
  },
  {
    id: 86,
    question: "You're on a road trip. You're miles from the next rest stop, but nature calls. What do you do?",
    answers: [
      { text: "Pull Over/Use Bush", points: 78 },
      { text: "Hold It In", points: 10 },
      { text: "Pee In Cup/Bottle", points: 6 },
      { text: "Drive Faster", points: 2 },
      { text: "Pee Out Window", points: 2 },
    ],
  },
  {
    id: 87,
    question: "We asked 100 women... Name an L word that describes how you feel on Valentine's Day.",
    answers: [
      { text: "Loved/Loving", points: 64 },
      { text: "Lonely", points: 27 },
      { text: "Lovely", points: 3 },
      { text: "Lucky", points: 2 },
      { text: "Liberated", points: 2 },
    ],
  },
  {
    id: 88,
    question: "Fill in the blank: After a divorce, it's always awkward to run into your ex's ______.",
    answers: [
      { text: "New Boo/Fling", points: 57 },
      { text: "Parents/Fam", points: 34 },
      { text: "Friends", points: 3 },
      { text: "Lawyer", points: 2 },
      { text: "Ex's Evil Face", points: 2 },
    ],
  },
  {
    id: 89,
    question: "Name a reason your hands might be tied behind your back.",
    answers: [
      { text: "Kidnapped/Robbery", points: 39 },
      { text: "Arrested", points: 36 },
      { text: "Fun W/ My Boo", points: 17 },
      { text: "Magic Trick", points: 3 },
      { text: "Bobbing For Apples", points: 3 },
    ],
  },
  {
    id: 90,
    question: "Name something your mom made you go to whether you wanted to or not.",
    answers: [
      { text: "Church/Bible Lesson", points: 58 },
      { text: "School", points: 30 },
      { text: "Relative's House", points: 3 },
      { text: "Store/Mall", points: 3 },
      { text: "Your Room/Bed", points: 3 },
    ],
  },
  {
    id: 91,
    question: "What would you do if you clogged a date's toilet?",
    answers: [
      { text: "Plunge/Fix It", points: 50 },
      { text: "Flee/Out Window", points: 18 },
      { text: "Tell 'Em/\"Sorry!\"", points: 17 },
      { text: "Cry/Die", points: 10 },
      { text: "Call A Plumber", points: 2 },
    ],
  },
  {
    id: 92,
    question: "Fill in the blank: Sally said, \"My ex broke my heart, so I broke his ______.\"",
    answers: [
      { text: "Car/Windshield", points: 35 },
      { text: "Face/Body", points: 29 },
      { text: "Bank Account", points: 25 },
      { text: "Phone", points: 5 },
      { text: "Spirit/Will To Live", points: 3 },
    ],
  },

  // ── 4-ANSWER SURVEYS ──────────────────────────────────────────────────────

  {
    id: 93,
    question: "Name something the dog sees you licking that it thinks, \"I want me some of that.\"",
    answers: [
      { text: "Ice Cream/Popsicle", points: 90 },
      { text: "Lollipop/Candy", points: 5 },
      { text: "Bone", points: 3 },
      { text: "My Lover", points: 2 },
    ],
  },
  {
    id: 94,
    question: "You'd fight with your neighbor if their what keeps getting in your yard?",
    answers: [
      { text: "Pet/Dog's Poop", points: 84 },
      { text: "Leaves/Tree", points: 10 },
      { text: "Car", points: 3 },
      { text: "Kids", points: 3 },
    ],
  },
  {
    id: 95,
    question: "Name something that's no good if it's not juicy.",
    answers: [
      { text: "Fruit/Orange", points: 74 },
      { text: "Steak/Meat", points: 20 },
      { text: "Gossip", points: 3 },
      { text: "Booty/Bod", points: 3 },
    ],
  },
  {
    id: 96,
    question: "Name the first person a woman would tell if she discovered her husband was cheating.",
    answers: [
      { text: "Friend", points: 70 },
      { text: "Mom", points: 17 },
      { text: "Sister", points: 9 },
      { text: "Lawyer", points: 4 },
    ],
  },
  {
    id: 97,
    question: "We asked 100 married men... Fill in the blank: If I were rich, my wife would never have to ______ again.",
    answers: [
      { text: "Work", points: 61 },
      { text: "Clean", points: 19 },
      { text: "Cook", points: 18 },
      { text: "Cheat", points: 2 },
    ],
  },
  {
    id: 98,
    question: "Name something a kid in a big family has to wait his turn to use.",
    answers: [
      { text: "Bathroom", points: 85 },
      { text: "Car", points: 8 },
      { text: "TV", points: 4 },
      { text: "Bike", points: 2 },
    ],
  },
  {
    id: 99,
    question: "Tell me something a couple does in public that shows you they like each other.",
    answers: [
      { text: "Hold Hands/Each Other", points: 69 },
      { text: "Kiss", points: 26 },
      { text: "Smile", points: 2 },
      { text: "Eat/Share Food", points: 2 },
    ],
  },
  {
    id: 100,
    question: "Name a job that requires wearing a white coat.",
    answers: [
      { text: "Doc/Dentist", points: 69 },
      { text: "Lab Tech/Scientist", points: 17 },
      { text: "Pharmacist", points: 11 },
      { text: "Butcher", points: 2 },
    ],
  },
  {
    id: 101,
    question: "Name something that gets put on ice.",
    answers: [
      { text: "Drinks/Champagne", points: 68 },
      { text: "Fish/Food", points: 15 },
      { text: "Bodies/Parts/Organs", points: 14 },
      { text: "Ice Skaters", points: 2 },
    ],
  },
  {
    id: 102,
    question: "When the zoo animals have a pool party, name an animal that might empty the pool when it jumps in.",
    answers: [
      { text: "Elephant", points: 66 },
      { text: "Hippo", points: 22 },
      { text: "Rhino", points: 9 },
      { text: "Hungry Gator/Croc", points: 2 },
    ],
  },
  {
    id: 103,
    question: "Name something that might be wrinkled.",
    answers: [
      { text: "Clothes/Shirt", points: 64 },
      { text: "Person/Skin", points: 30 },
      { text: "Prune/Fruit", points: 3 },
      { text: "The Sheets", points: 2 },
    ],
  },
  {
    id: 104,
    question: "Name an Italian food item that's popular in the U.S.",
    answers: [
      { text: "Pizza", points: 48 },
      { text: "Pasta", points: 47 },
      { text: "Meatballs", points: 2 },
      { text: "Chicken Parm", points: 2 },
    ],
  },
  {
    id: 105,
    question: "A broke couple asked their wedding guests to bring their own what?",
    answers: [
      { text: "Booze/Drinks", points: 75 },
      { text: "Cake/Food", points: 17 },
      { text: "Cash For The Bar", points: 4 },
      { text: "Chairs", points: 3 },
    ],
  },
];
